name: nixos-cfgs-nixbuild-ci


on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    uses: nixbuild/nixbuild-action/.github/workflows/ci-workflow.yml@v19
    secrets:
      nixbuild_ssh_key: ${{ secrets.nixbuild_ssh_key }}
    with:
      flake_directory: ./nixos-configurations
      filter_builds: '.top_attr == "packages"'
