name: nixos-cfgs-nixbuild


on:
  pull_request:
  push:
    branches:
      - main


jobs:

  build-nixos:
    name: Build NixOS Configs
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - uses: nixbuild/nix-quick-install-action@v24
        with:
          nix_on_tmpfs: true
          nix_conf: |
            experimental-features = nix-command flakes

      - uses: nixbuild/nixbuild-action@v19
        with:
          nixbuild_ssh_key: ${{ secrets.nixbuild_ssh_key }}

      - name: Build NixOS Configs
        working-directory: nixos-configurations
        run: |
          nix build -L \
            --eval-store auto --store ssh-ng://eu.nixbuild.net \
            .#dell-xps \
            .#tongfang-amd
